### ISSUE TITLE
1 | p(print, "%s" %px) does not work as intended

### ISSUE THREAD

**Issue by rcodo** [sspipe/sspipe#10]
from sspipe import p, px
1 | p(print, "%s" %px)
2 | p(print, "{}".format(px)) not work either

**Comment by mhsekhavat** [comment]
Currently, because of some limitations in python, `px` only works with, arithmatic operators (+,-, etc.) and `numpy` functions. For other functions, you can use lambda. All of the following examples would work.

```python
1 | p(lambda x: print("%s" % x))
2 | p(lambda x: "{}".format(x))
```

Furthermore, there are easier ways to get the same result as well:

```python
1 | p(print, "%s", px)  # notice that there is a comma between "%s" and px.
2 | p("{}".format)
```
