### ISSUE TITLE
Stuck when zipping

### ISSUE THREAD

**Issue by Shoggomo** [sspipe/sspipe#12]
I'm trying to zip/unzip an array, but the console always hangs up. Is this a bug, or am I doing something wrong?

```python
from sspipe import p, px

[[1, 2, 3], [4, 5, 6]] | p(zip, px)       # zip, console/notebook gets stuck
[[1, 2], [3, 4], [5, 6]] | p(zip, *px)    # unzip, console/notebook gets stuck
```

**Comment by mhsekhavat** [comment]
> [[1, 2, 3], [4, 5, 6]] | p(zip, px)       # zip, console/notebook gets stuck

This line is correct. It doesn't hang up in my environment, and is equivalent to `zip([[1, 2, 3], [4, 5, 6]])`.

> [[1, 2], [3, 4], [5, 6]] | p(zip, *px)    # unzip, console/notebook gets stuck

This line is incorrect, as `px` doesn't support arbitrary operations. You can use `p(lambda x: ...)` instead:

```python
[[1, 2], [3, 4], [5, 6]] | p(lambda x: zip(*x))
```
