### ISSUE TITLE
AttributeError: module 'pipe' has no attribute '__all__'

### ISSUE THREAD

**Issue by dyangny** [sspipe/sspipe#13]
`from sspipe import p, px`
throws the error:
`AttributeError: module 'pipe' has no attribute '__all__'`

**Comment by ringeringeraja** [comment]
I solved it downgrading the "pipe" dependency to version 1.6.0.

**Comment by mohammad7t** [comment]
Thanks for reporting the dependency issue. The issue is fixed in sspipe>=0.1.17.
