### ISSUE TITLE
A composition framework that involves sspipe

### ISSUE THREAD

**Issue by eyalk11** [sspipe/sspipe#14]
Hi,
I have built such python framework that allows for composition of functions .  sspipe really enables me to take the next level. 
I also did a fork with name and contextvars feature (needed). Let me know if you would include it (it  is backward-comptabile, but won't add value without the entire framework). Could do a PR.

And also wanted to hear WDYT and if you would recommend it ,  that would be appreciated. 

https://github.com/eyalk11/composition

Thanks.

**Comment by mohammad7t** [comment]
Hi @eyalk11,

Thanks for sharing your use case. Glad to hear sspipe has been helpful for your framework!

Regarding name/contextvars, as you mentioned about the value, I think it's better to keep that in your fork at this stage. We can reconsider it after finding more use cases.
