### ISSUE TITLE
Include sspipe module as part of the Standard Library

### ISSUE THREAD

**Issue by jtelleriar** [sspipe/sspipe#4]
Could sspipe module be included as part of the standard library?

We want piping to be a first class citizen within Python itself:

https://bugs.python.org/issue38052

Here is what they have asked to provide:

```
Before proposing a third party module for inclusion in the standard library, you should check:

- is the module mature and stable?

- does it have an FOSS licence compatible with Python, and if not, are the authors willing to re-licence it?

- are the authors willing to donate the module to Python?

- are the authors happy to change their release schedule to match Python?

- are they happy to adhere to Python's policy on backwards compatibility and new functionality?

- are you (or the authors) willing to write a PEP proposing to add this module to the standard library? https://www.python.org/dev/peps/

- can you find a Core Developer willing to sponsor this PEP? (You can probably ask on the Python-Dev or Python-Ideas mailing lists, or the Python Discuss, or face-to-face in person at a sprint, etc.)

Only after you have done all those things, and got Yes answers to them all, should you propose adding the module. (A single No means there is no chance.)

```

**Comment by mhsekhavat** [comment]
Hi @jtelleriar 

Thank you for your efforts on making pipes a first-class citizen! 

> - is the module mature and stable?
I am using this module in my own projects for a while and it satisfies my own requirements. However, I think if we want to propose it as a PEP, we should plan for a 1.0.0 release with some improvements on the API and documentation and tests.

> - does it have an FOSS licence compatible with Python, and if not, are the authors willing to re-licence it?
The author is willing to re-licence it.

> - are the authors willing to donate the module to Python?
Yes

> - are the authors happy to change their release schedule to match Python?
Yes

> - are they happy to adhere to Python's policy on backwards compatibility and new functionality?
Yes

> - are you (or the authors) willing to write a PEP proposing to add this module to the standard library? https://www.python.org/dev/peps/
Yes, with your contribution.

> - can you find a Core Developer willing to sponsor this PEP? (You can probably ask on the Python-Dev or Python-Ideas mailing lists, or the Python Discuss, or face-to-face in person at a sprint, etc.)
We may try.

**Comment by mhsekhavat** [comment]
@jtelleriar Thank you for your efforts. But I found the reasons not to propose a PEP quite sound.

**Comment by jtelleriar** [comment]
Agree.

Thank you.
