### ISSUE TITLE
pipe iterator into next function

### ISSUE THREAD

**Issue by JoshZastrow** [sspipe/sspipe#9]
sspipe hangs up when the output is an iterator and the next function iterates over the prior output.

```reduce(lambda x, y: x + y, [1, 2, 3, 4])``` yields 10 but  ```[1, 2, 3, 4] | reduce(lambda x, y: x + y, px)``` hangs up

```[x + 1 for x in [1, 2, 3, 4]]``` yields [2, 3, 4, 6] but ```[1, 2, 3, 4] | [x + 1 for x in px]``` hangs up

Would love a way to pass iterators!

**Comment by JoshZastrow** [comment]
Actually I should have read the docs closer! 

I see how `[1, 2, 3, 4]  | p(map, px + 1)` works as list comprehension would, but I can't do dictionary comprehension or use the `reduce` function for that matter.

Perhaps I'm not using the library correctly?

**Comment by mhsekhavat** [comment]
Thanks for your feedback.
Currently, sspipe supports `p(map, px)` and `p(filter, px)` natively, but it doesn't support `p(reduce, px)` natively yet. But you can use still use it with reduce like this:

```python
>>> [1, 2, 3, 4] | p(lambda l: reduce(lambda x, y: x+y, l))
10
```

For dict comprehension, you can generate a list of [key, value] pairs and pass it to dict:
```python
>>> [1, 2, 3, 4] | p(map, p([p(str), px%2])) | p(dict)
{'1': 1, '2': 0, '3': 1, '4': 0}
```
